ALTER TABLE class_adjustments
  ADD COLUMN is_mutual BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN mutual_date DATE DEFAULT NULL,
  ADD COLUMN mutual_day VARCHAR(20) DEFAULT NULL,
  ADD COLUMN mutual_from_time TIME DEFAULT NULL,
  ADD COLUMN mutual_to_time TIME DEFAULT NULL,
  ADD COLUMN mutual_subject_name VARCHAR(200) DEFAULT NULL,
  ADD COLUMN mutual_section VARCHAR(50) DEFAULT NULL;
